import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SocketProvider } from "@/components/socket-provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { MainNav } from "@/components/main-nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

//REVIEW: metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "antialiased min-h-screen bg-background dark:bg-background",
          inter.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // REVIEW:
          disableTransitionOnChange
        >
          <MainNav />

          <SocketProvider>
            <Toaster />
            <main className="py-24 min-h-screen">{children}</main>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
